title:            SmileCat's Blog
description:      The endless quitter's blog.

# put your disqus here
disqus_shortname: egaoneko
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             /assets/ico/favicon-96x96.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://www.3daysofprogramming.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Pinned'
    url: '#'
    submenu:
      - title: 'JavaScript'
        url: '/categories#javascript'
      - title: 'Frontend'
        url: '/categories#frontend'
  - title: 'Playground'
    url: '/playground'

# Owner/author information
owner:
  name:           SmileCat
  site:           /about
  avatar:         /images/logo.jpg
  bio:            "How do you define yourself?"
  email:          donghyun.seo91@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter:        frank_seo
  # GitHub nick for use in follow button in author block.
  github:         egaoneko

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:          frank_seo

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/egaoneko"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/donghyunseo"
  - title: "twitter"
    url: "https://twitter.com/frank_seo"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-62717870-1
google_verify: google1bca872409dc6831
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Seoul
locale:      ko_KR
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title.html

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", ".travis.yml","cibuild"]
plugins: [jekyll-paginate]
# theme: neo-hpstr-jekyll-theme

sitemap:
  lastmod: 2014-01-23
  priority: 0.7
  changefreq: 'monthly'
  url: 'https://egaoneko.github.io'
  exclude: 'yes'
