# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md",".travis.yml","cibuild",vendor] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: egaoneko
google_analytics: UA-62717870-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: SmileCat's Blog

description: SmileCat's Blog
author:
  name: Donghyun Seo
  email: egaoneko@naver.com
  github: egaoneko
  twitter:
  pinterest:
  linkedin: donghyunseo
  bio: How do you define yourself?
  email_md5:

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-coffeescript
- jekyll-paginate
- jekyll-gist

sitemap:
  lastmod: 2014-01-23
  priority: 0.7
  changefreq: 'monthly'
  url: 'http://egaoneko.github.io'
  exclude: 'yes'
